# Generated by Django 4.2.6 on 2023-10-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassifierModel', '0002_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_data', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
