# Generated by Django 4.2.6 on 2023-10-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassifierModel', '0003_modelfile_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelFile',
        ),
    ]
